export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST';
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS';
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';


export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAIL = 'ORDER_CANCEL_FAIL';

export const GET_ALL_ORDERS_ADMIN_REQUEST = 'GET_ALL_ORDERS_ADMIN_REQUEST';
export const GET_ALL_ORDERS_ADMIN_SUCCESS = 'GET_ALL_ORDERS_ADMIN_SUCCESS';
export const GET_ALL_ORDERS_ADMIN_FAIL = 'GET_ALL_ORDERS_ADMIN_FAIL';


export const UPDATE_ORDER_STATUS_REQUEST  = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS  = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL  = "UPDATE_ORDER_STATUS_FAIL";