export const CREATE_POSTER_REQUEST = "CREATE_POSTER_REQUEST"
export const CREATE_POSTER_SUCCESS = "CREATE_POSTER_SUCCESS"
export const CREATE_POSTER_FAIL = "CREATE_POSTER_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"