export const CREATE_POSTER_REQUEST = "CREATE_POSTER_REQUEST"
export const CREATE_POSTER_SUCCESS = "CREATE_POSTER_SUCCESS"
export const CREATE_POSTER_FAIL = "CREATE_POSTER_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const GET_POSTER_REQUEST = "GET_POSTER_REQUEST"
export const GET_POSTER_SUCCESS = "GET_POSTER_SUCCESS"
export const GET_POSTER_FAIL = "GET_POSTER_FAIL"